apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  name: doriscluster-local
  namespace: doris
spec:
  feSpec:
    replicas: 1
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi
    image: apache/doris:fe-3.1.4
    envVars:
      - name: FE_SERVERS
        value: "fe1:127.0.0.1:9010"
  beSpec:
    replicas: 1
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi
    image: apache/doris:be-3.1.4
    envVars:
      - name: BE_ADDR
        value: "127.0.0.1:9050"
      - name: FE_HOST
        value: "127.0.0.1"
      - name: FE_PORT
        value: "9030"
