PROXY_PORT = 9080
HTTP_PORT = 8030
QUERY_PORT = 9030
RPC_PORT = 9020
EDIT_LOG_PORT = 9010
priority_networks = 172.20.0.0/16

meta_dir = /opt/doris/fe/doris-meta
LOG_DIR = /opt/doris/fe/log

JAVA_OPTS="-Xmx2048m -Xms2048m -Xmn768m -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:$LOG_DIR/fe.gc.log.$DATE"

http_port = 8030
rpc_port = 9020
query_port = 9030
edit_log_port = 9010
mysql_service_nio_enabled = true

enable_fqdn_check = false

frontend_health_check_interval_seconds = 10

max_connection = 1000

cluster_name = doris_cluster

storage_root_path = /opt/doris/fe/doris-meta

heartbeat_interval_second = 10
heartbeat_timeout_second = 30

check_java_version = false

enable_https = false

enable_auth = true

default_password_cluster = ""

enable_bdbje_debug_mode = false

meta_delay_toleration_second = 10

enable_token_check = true

enable_deploy_manager = true
