# FoundationDB 配置文件

[general]
kill_on_configuration_change = false

[fdbserver]
command = /usr/sbin/fdbserver
cluster_file = /etc/foundationdb/fdb.cluster
seed_cluster_file = /etc/foundationdb/fdb.cluster
public_address = auto:$FDB_PORT
datadir = /var/lib/foundationdb/data
logdir = /var/log/foundationdb
logsize = 100MiB
maxlogssize = 1GiB
