apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  name: test-cluster
  namespace: doris
spec:
  feSpec:
    replicas: 1
    image: apache/doris:2.1.5
    resources:
      requests:
        cpu: 1
        memory: 2Gi
  beSpec:
    replicas: 1
    image: apache/doris:2.1.5
    resources:
      requests:
        cpu: 1
        memory: 2Gi