PPROF_PORT = 8040
WEB_SERVER_PORT = 8040
HEARTBEAT_SERVICE_PORT = 9050
BRPC_PORT = 9060
THRIFT_SERVER_PORT = 9060
priority_networks = 172.20.0.0/16

storage_root_path = /opt/doris/be/storage
LOG_DIR = /opt/doris/be/log

JAVA_OPTS="-Xmx4096m -Xms4096m -Xmn1536m -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:$LOG_DIR/be.gc.log.$DATE"

webserver_port = 8040
heartbeat_service_port = 9050
brpc_port = 9060
thrift_server_port = 9060

heartbeat_interval_second = 10
heartbeat_timeout_second = 30

storage_flood_stage_usage_percent = 85
storage_flood_stage_left_capacity_bytes = 1073741824

mem_limit = 80%

default_rowset_type = BETA

disable_storage_page_cache = false

storage_page_cache_limit = 20%

disable_memtable_on_disk_segment = false

max_tablet_version_num = 1000

max_compaction_threads = 4

max_tablet_compaction_threads = 4

min_compaction_threads = 2

compaction_task_num_per_disk = 2

max_rowset_meta_memory_usage_percentage = 20

enable_stream_load = true

enable_spilling = true

enable_auto_compaction = true

enable_new_importer = true

enable_pipeline_load = true

enable_pipeline_engine = true
